name: Terraform Dev Deployment (OIDC)

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Choose Service'
        required: true
        type: choice
        options:
          - vpc
          - ec2
          - all
      action:
        description: 'Choose Terraform Action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write     # REQUIRED for OIDC
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ROLE_TO_ASSUME: arn:aws:iam::427814062472:role/github-terraform-dev-role

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Clean Terraform Cache
        run: rm -rf .terraform .terraform.lock.hcl

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve